---
title: "PCAngsd_Analysis"
author: "Alyssa Green"
date: "`r Sys.Date()`"
output: html_document
---

Load Libraries
```{r}
library(RcppCNPy)
library(dplyr)
library(qqman) #for man plot can remove dosent work
library(ggplot2)
library(tidyr)
source("http://bit.ly/theme_pub")
```

Load Data
```{r}
#Load in .npy file
npy_dat<- npyLoad("try2_selection.selection.npy")

#Load in .sites file
sites<-read.table("kittiwake.sites", row.names = NULL)
names(sites)<-c("chromosome","marker")

#Load in alternate 0/1 .sites file
alt_sites<-read.table("try2_selection.sites")

#Load Genes File
Genes=read.csv("Genes.csv")
```

Create QQplot to QC Test Statistics
```{r}
#Run qqchi function
source("./Functions/qqchi_func.R")
qqchi(npy_dat)
```

Convert Test Statistics to p-values
```{r}
pval=1-pchisq(npy_dat,1)
pval=as.data.frame(pval)
```

Combine 2 .sites files
```{r}
sites$V1=alt_sites$V1
```

Remove elements of .sites values where V1=0
```{r}
sig=sites%>%filter(V1==1)
```

Create data frame combining sites and pvals
```{r}
Combo=data.frame(marker=sig$marker, chromosome=sig$chromosome, pval1=pval$V1, pval2=pval$V2)
```

Select genes of interest
```{r}
Interest_Dat=Combo[(Combo$chromosome %in% Genes$Code),]
```


```{r}
dat=Interest_Dat%>%filter(marker==1)
ggplot(data=dat, aes(x=chromosome, y=-log10(pval1)))+geom_point()+geom_hline(yintercept=-log10(0.05))
```



Attempt 4

```{r}
dat=at2%>%filter(marker==1)
ggplot(data=dat, aes(x=chromosome, y=-log10(pval)))+geom_point()+geom_hline(yintercept=-log10(0.05))
```
Attempt 5: Works but need to find a way to label graphs
```{r}
for (i in c(1:46211612)) {
dat=at2%>%filter(marker==i)
graph=ggplot(data=Filtered_Dat, aes(x=chromosome, y=-log10(pval)))+geom_point()+geom_hline(yintercept=-log10(0.05))+theme_pub()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
print(graph)
}
```

```{r}
for (i in c(31:50)) {
dat=Interest_Dat%>%filter(marker==i)
graph=ggplot(data=dat, aes(x=chromosome, y=-log10(pval1)))+geom_point()+geom_hline(yintercept=-log10(0.05))+theme_pub()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
print(graph)
}
```
VZUC01000049.1:11
VZUC01000080.1:16
VZUC01000057.1:28
VZUC01000451.1:32
VZUC0100022201:49


FIlter data
```{r}
Filtered_Dat=at2[(at2$chromosome %in% Genes$Code),]
Grouped=Filtered_Dat%>%group_by(chromosome)
```

